openapi: 3.0.1

info:
  title: GPT2-TedTalk
  version: 1.0.0
  contact:
    name: Dalton Burke
  description: |
    Generate Ted Talks with the GPT-2 model
    ---
          How to use:
          * First, provide some text, this will be base of the Ted Talk.
          * Then, specify the length of the output text. I recommend between 100 and 300.
          * If the length is too big, it may take a long time to generate.
    ---
servers:
  - url: https://master-ainize-gpt2-tedtalk-dmtburke.endpoint.ainize.ai

paths:
  /predict:
    post:
      requestBody:
        required: true
        description: |
          This request will generate Ted Talk text, based on what the user provides.
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                base_text:
                  type: string
                  description: "Base Text"
                length:
                  type: string
                  description: "Length"
              required:
                - base_text
                - length
      responses: # Set response
        '200':
          description: "Successful Response"
          content:
            application/json:
              schema:
                type: object
        '400':
          description: "Bad Request Error"
        '429':
          description: "Too many requests"
        '500':
          description: "Server-side Error"
